import Vue from "vue";
import Attribution from "src/components/Attribution.vue";
import ExternalLink from "src/components/ExternalLink.vue";
import GlobalSnackbar from "src/components/GlobalSnackbar.vue";
import ListAnswer from "src/components/ListAnswer.vue";
import ListQuestion from "src/components/ListQuestion.vue";
import LoadableButton from "src/components/LoadableButton.vue";
import LoadableTooltipIconButton from "src/components/LoadableTooltipIconButton.vue";
import Loader from "src/components/Loader.vue";
import TabList from "src/components/TabList.vue";
import Tag from "src/components/Tag.vue";
import TopMenu from "src/components/TopMenu.vue";
import UserActivity from "src/components/UserActivity.vue";
import UserInfo from "src/components/UserInfo.vue";
Vue.component("attr", Attribution);
Vue.component("ax", ExternalLink);
Vue.component("GlobalSnackbar", GlobalSnackbar);
Vue.component("ListAnswer", ListAnswer);
Vue.component("ListQuestion", ListQuestion);
Vue.component("LoadableButton", LoadableButton);
Vue.component("LoadableTooltipIconButton", LoadableTooltipIconButton);
Vue.component("Loader", Loader);
Vue.component("TabList", TabList);
Vue.component("Tag", Tag);
Vue.component("TopMenu", TopMenu);
Vue.component("UserActivity", UserActivity);
Vue.component("UserInfo", UserInfo);